### ISSUE TITLE
Adding Awesome Python in Education to Awesome

### ISSUE THREAD

**Issue by Danix421** [quobit/awesome-python-in-education#36]
Hi Awesome Python in Learning, i'm Danix, a developer. I viewed that this Awesome list is not in the big [Awesome](https://awesome.re/) list. I wan't to contribute (again) to this list by creating a pull request in the big Awesome list to add this to it! (I think) this will make Awesome Python in Education more famous, why the big Awesome list is the original Aweosme, the Awesome of the Awesomes. Well, i hope Awesome Python in Education give me permission to do it!

**Comment by quobit** [comment]
Of course! Although it would be also interesting appearing in vinta/awesome-python

**Comment by Danix421** [comment]
Ok, i will advise in this way when i open the pull request in Awesome and when (if they like it) accept it. In vinta/awesome-python i will do it too! Thanks.

**Comment by Danix421** [comment]
Well, i already have a pull request in vinta/awesome-python so i will add this commit to it! You can view it [here](https://github.com/vinta/awesome-python/pull/1733). Please, view it and add vote, why i'm waited for more of 10 days for a review and it don't have one why vinta only wan't to review a pull request that haves minimum 20 votes.

**Comment by Danix421** [comment]
The Awesome pull request is now created. You can view it [here](https://github.com/sindresorhus/awesome/pull/1961).

**Comment by Danix421** [comment]
Sorry, quobit, but the Awesome creator, sindresorhus, saw that your list don't meet his guidelines to be displayed in his Awesome. Sorry again, but you will have to modify your list to meet the guidelines. Someone in my pull request has saw to use something named Awesome Lint to know what are the requirements that your list don't meet. You can view his menssage [here](https://github.com/sindresorhus/awesome/pull/1961#issuecomment-792802735) to do the changes.

**Comment by Danix421** [comment]
[This](https://github.com/quobit/awesome-python-in-education/pull/38) is the pull request that fix it, i think.

**Comment by Danix421** [comment]
Sorry, @quobit but the owner of Awesome closed the Awesome Python in Education pull request, i think that was why we breaked some of the Awesome guidelines. The vinta/awesome-python pull request has not closed but it has too much time open and vinta don't review it, so, that are bad news.

**Comment by Danix421** [comment]
Sorry, @quobit, but were is not respond from vinta, so i will close the pull request

**Comment by quobit** [comment]
No problem at all. Thank you for your interest
